# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 08:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 17, 8, 55, 38, 928410, tzinfo=utc)),
        ),
    ]
